import { Inter } from "next/font/google";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import profilePic from "../../public/profile-pic.jpg";
import runitup from "../../public/runitupPic.jpg";
import roboT from "../../public/robotrainerPic.jpg";
import portfolio from "../../public/portfolioPic.jpg"
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // DARK MODE IMPLEMENTATION
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Moeed Chaudhry</title>
        <meta name="description" content="Generated by" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-x font-burtons">Made by Moeed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Moeed Chaudhry
            </h2>
            <h3 className="text-2xl md:text-3xl py-2">
              Computer Science Student@ Virginia Tech
            </h3>
            <p1 className="text-md md:text-xl py-5 leading-8 text-gray-800 max-w-lg mx-auto dark:text-teal-500">
              Expected Graduation: Dec 2023
            </p1>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/moeed-chaudhry-bb8535165/" target="_blank">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/MoeedCh" target="_blank">
              <AiFillGithub />
            </a>
            
          </div>
          <div className="mx-auto relative bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-7 overflow-hidden">
            <Image src={profilePic} layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* SECOND PAGE BELOW */}

        <section>
          <div>
            <h3 className="text-3xl py-1"> Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-80">
              BLANKET TEXT OF WHAT IT IS OFFER.{" "}
              <span className="text-teal-500">I CAN RESTRUCTURE LATER.</span>{" "}
              END P TAG
            </p>
          </div>

          {/* CARD SYSTEM BELOW */}

          <div className="lg:flex gap-10 justify-center">
            <div className="text-center shadow-lg p-10 rounded my-10">
              <Image src={runitup} width={250} height={150} className="rounded-lg" />
              <h3 className="text-lg font-med pt-8 pb-2">RunItUp</h3>
              <p className="py-2">Developed during VTHACKS X</p>
              <h4 className="py-4 text-teal-600">The Stack: </h4>
              <p className="text-gray-800 py-1 dark:text-white">Python</p>
              <p className="text-gray-800 py-1 dark:text-white">FireBase</p>
              <p className="text-gray-800 py-1 dark:text-white">Google Maps API</p>
              <p className="text-gray-800 py-1 dark:text-white">TKinter</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className="flex justify-center">
                 <Image src={roboT} width={200} height={100} className="rounded-lg" />
              </div>
              
              <h3 className="text-lg font-med pt-8 pb-2">RoboTrainer</h3>
              <p className="py-2">
                Developed during VTHACKS IX. Produces personalized lifting 
                programs based off a short survey filled out by the user.
              </p>
              <h4 className="py-4 text-teal-600">The Stack I used: </h4>
              <p className="text-gray-800 py-1 dark:text-white">Python</p>
              <p className="text-gray-800 py-1 dark:text-white">Flask</p>
              <p className="text-gray-800 py-1 dark:text-white">SQLAlchemy</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={portfolio} width={250} height={100} className="rounded-lg"/>
              <h3 className="text-lg font-med pt-8 pb-2">Portfolio Website</h3>
              <p className="py-2">
                Developed to practice using JavaScript and learn Tailwind CSS.
              </p>
              <h4 className="py-4 text-teal-600">The Stack I used: </h4>
              <p className="text-gray-800 py-1 dark:text-white">Next.js</p>
              <p className="text-gray-800 py-1 dark:text-white">Tailwind CSS</p>
              <p className="text-gray-800 py-1 dark:text-white">Git</p>
            </div>
          </div>
        </section>

        {/* THIRD SECTION BELOW */}

        {/* <section>
          <div>
            <h3 className="text-3xl py-1"> Portfolio </h3>
          </div>
        </section> */}
      </main>
    </div>
  );
}
